# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 709384b46e615b5afde728f9228c6f794132a7a9055060bd274442ea7ddfb01f070ea41882caf57385f80d4cafe9068f86c08501336f742597d9dbdac3a88cb7

test:
  secret_key_base: a7b17ec5b337f3b3ffbe587cf5dab0f016988112b76f56618201e468348b12bbed31a472da1222a1e6955b4511c2834ead5cae23eebeda870060bd8b46ffc3e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
